// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOiauHiPo_NVFOGOjXFYhXt3W2_kKOdYI',
    appId: '1:448618578101:web:0b650370bb29e29caa7fd9',
    messagingSenderId: '448618578101',
    projectId: 'sleepmusic-47e91',
    authDomain: 'sleepmusic-47e91.firebaseapp.com',
    storageBucket: 'sleepmusic-47e91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzqYxFo8lWAtgJUlq-ffbQQrQRoGl6W3Q',
    appId: '1:684753848387:android:d1937c14030858a7df6cf6',
    messagingSenderId: '684753848387',
    projectId: 'sleep-music-cfab6',
    storageBucket: 'sleep-music-cfab6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC95p-BRYKJoKEH6nfUOQVCAB9ZLw8Wd4Q',
    appId: '1:684753848387:ios:a254c8fa6ade3b77df6cf6',
    messagingSenderId: '684753848387',
    projectId: 'sleep-music-cfab6',
    storageBucket: 'sleep-music-cfab6.firebasestorage.app',
    iosClientId:
        '448618578101-abc123def456ghi789jkl012mno345pq.apps.googleusercontent.com',
    iosBundleId: 'com.maviqus.SleepMusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3g4Q5fYk5X8_9fYp6y8WY1X2fKYm5fYp',
    appId: '1:448618578101:ios:2b17e314f88cfeaaaa7fd9',
    messagingSenderId: '448618578101',
    projectId: 'sleepmusic-47e91',
    storageBucket: 'sleepmusic-47e91.appspot.com',
    iosClientId:
        '448618578101-abc123def456ghi789jkl012mno345pq.apps.googleusercontent.com',
    iosBundleId: 'com.maviqus.SleepMusic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOiauHiPo_NVFOGOjXFYhXt3W2_kKOdYI',
    appId: '1:448618578101:web:0b650370bb29e29caa7fd9',
    messagingSenderId: '448618578101',
    projectId: 'sleepmusic-47e91',
    authDomain: 'sleepmusic-47e91.firebaseapp.com',
    storageBucket: 'sleepmusic-47e91.appspot.com',
  );
}
